# ProyectoSQL

Los pasos que voy a seguir en esta parte del proceso son: 
  
1. Asignar a cada csv un nombre que lo relacione con su contenido.
2. Limpiar los nulos de la tabla.
3. Ver si hay valores repetidos.
4. Ver si hay consistencia en los datos.
5. Exportar a fichero csv limpio.
  
Una vez realizado estos pasos con cada csv pasaré a realizar el esquema en MySQL Workbench 

# Actors
---

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')   # para quitar esos prints

In [5]:
actors = pd.read_csv('../data/actor.csv')
actors.head()

actor_id first_name     last_name          last_update
0         1   PENELOPE       GUINESS  2006-02-15 04:34:33
1         2       NICK      WAHLBERG  2006-02-15 04:34:33
2         3         ED         CHASE  2006-02-15 04:34:33
3         4   JENNIFER         DAVIS  2006-02-15 04:34:33
4         5     JOHNNY  LOLLOBRIGIDA  2006-02-15 04:34:33

In [6]:
actors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   actor_id     200 non-null    int64 
 1   first_name   200 non-null    object
 2   last_name    200 non-null    object
 3   last_update  200 non-null    object
dtypes: int64(1), object(3)
memory usage: 6.4+ KB


In [11]:
actors.isna().sum()

actor_id       0
first_name     0
last_name      0
last_update    0
dtype: int64

In [12]:
actors.drop_duplicates(inplace = True)

In [13]:
actors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   actor_id     200 non-null    int64 
 1   first_name   200 non-null    object
 2   last_name    200 non-null    object
 3   last_update  200 non-null    object
dtypes: int64(1), object(3)
memory usage: 6.4+ KB


In [22]:
actors['last_update'] = pd.to_datetime(actors['last_update'], format='%Y-%m-%d %H:%M:%S')

In [29]:
actors.last_update.unique()

<DatetimeArray>
['2006-02-15 04:34:33']
Length: 1, dtype: datetime64[ns]

In [31]:
actors.drop('last_update', axis=1, inplace=True)

In [32]:
actors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   actor_id    200 non-null    int64 
 1   first_name  200 non-null    object
 2   last_name   200 non-null    object
dtypes: int64(1), object(2)
memory usage: 4.8+ KB


In [33]:
actors.head()

actor_id first_name     last_name
0         1   PENELOPE       GUINESS
1         2       NICK      WAHLBERG
2         3         ED         CHASE
3         4   JENNIFER         DAVIS
4         5     JOHNNY  LOLLOBRIGIDA

In [34]:
actors.to_csv('../data/limpios/actors_limpio.csv', index=False)

# Category
---

In [26]:
cat = pd.read_csv('../data/category.csv')
cat.head()

category_id       name          last_update
0            1     Action  2006-02-15 04:46:27
1            2  Animation  2006-02-15 04:46:27
2            3   Children  2006-02-15 04:46:27
3            4   Classics  2006-02-15 04:46:27
4            5     Comedy  2006-02-15 04:46:27

In [27]:
cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   category_id  16 non-null     int64 
 1   name         16 non-null     object
 2   last_update  16 non-null     object
dtypes: int64(1), object(2)
memory usage: 512.0+ bytes


In [28]:
cat.last_update.unique()

array(['2006-02-15 04:46:27'], dtype=object)

In [35]:
cat.drop('last_update', axis=1, inplace=True)

In [81]:
cat.drop_duplicates(inplace = True)

In [82]:
cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   category_id  16 non-null     int64 
 1   name         16 non-null     object
dtypes: int64(1), object(1)
memory usage: 384.0+ bytes


In [37]:
cat.to_csv('../data/limpios/categories_limpio.csv', index=False)

# Film
---

In [38]:
film = pd.read_csv('../data/film.csv')
film.head()

film_id             title   
0        1  ACADEMY DINOSAUR  \
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  release_year   
0  A Epic Drama of a Feminist And a Mad Scientist...          2006  \
1  A Astounding Epistle of a Database Administrat...          2006   
2  A Astounding Reflection of a Lumberjack And a ...          2006   
3  A Fanciful Documentary of a Frisbee And a Lumb...          2006   
4  A Fast-Paced Documentary of a Pastry Chef And ...          2006   

   language_id  original_language_id  rental_duration  rental_rate  length   
0            1                   NaN                6         0.99      86  \
1            1                   NaN                3         4.99      48   
2            1                   NaN                7         2.99      50   
3            1                   NaN                5         2.99     117   
4            1                   NaN                6         2.99     130   

   replacement_cost rating                  special_features   
0             20.99     PG  Deleted Scenes,Behind the Scenes  \
1             12.99      G           Trailers,Deleted Scenes   
2             18.99  NC-17           Trailers,Deleted Scenes   
3             26.99      G    Commentaries,Behind the Scenes   
4             22.99      G                    Deleted Scenes   

           last_update  
0  2006-02-15 05:03:42  
1  2006-02-15 05:03:42  
2  2006-02-15 05:03:42  
3  2006-02-15 05:03:42  
4  2006-02-15 05:03:42

In [39]:
film.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   film_id               1000 non-null   int64  
 1   title                 1000 non-null   object 
 2   description           1000 non-null   object 
 3   release_year          1000 non-null   int64  
 4   language_id           1000 non-null   int64  
 5   original_language_id  0 non-null      float64
 6   rental_duration       1000 non-null   int64  
 7   rental_rate           1000 non-null   float64
 8   length                1000 non-null   int64  
 9   replacement_cost      1000 non-null   float64
 10  rating                1000 non-null   object 
 11  special_features      1000 non-null   object 
 12  last_update           1000 non-null   object 
dtypes: float64(3), int64(5), object(5)
memory usage: 101.7+ KB


In [41]:
film.drop('original_language_id', axis=1, inplace=True)

In [42]:
film.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   film_id           1000 non-null   int64  
 1   title             1000 non-null   object 
 2   description       1000 non-null   object 
 3   release_year      1000 non-null   int64  
 4   language_id       1000 non-null   int64  
 5   rental_duration   1000 non-null   int64  
 6   rental_rate       1000 non-null   float64
 7   length            1000 non-null   int64  
 8   replacement_cost  1000 non-null   float64
 9   rating            1000 non-null   object 
 10  special_features  1000 non-null   object 
 11  last_update       1000 non-null   object 
dtypes: float64(2), int64(5), object(5)
memory usage: 93.9+ KB


In [43]:
film.release_year.unique()

array([2006], dtype=int64)

In [44]:
film.drop('release_year', axis=1, inplace=True)

In [45]:
film.language_id.unique()

array([1], dtype=int64)

In [46]:
film.drop('language_id', axis=1, inplace=True)

In [47]:
film.last_update.unique()

array(['2006-02-15 05:03:42'], dtype=object)

In [48]:
film.drop('last_update', axis=1, inplace=True)

In [83]:
film.drop_duplicates(inplace = True)

In [84]:
film.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   film_id           1000 non-null   int64  
 1   title             1000 non-null   object 
 2   description       1000 non-null   object 
 3   rental_duration   1000 non-null   int64  
 4   rental_rate       1000 non-null   float64
 5   length            1000 non-null   int64  
 6   replacement_cost  1000 non-null   float64
 7   rating            1000 non-null   object 
 8   special_features  1000 non-null   object 
dtypes: float64(2), int64(3), object(4)
memory usage: 70.4+ KB


In [55]:
film.to_csv('../data/limpios/film_limpio.csv', index=False)

# Inventory
---

In [56]:
inv = pd.read_csv('../data/inventory.csv')
inv.head()

inventory_id  film_id  store_id          last_update
0             1        1         1  2006-02-15 05:09:17
1             2        1         1  2006-02-15 05:09:17
2             3        1         1  2006-02-15 05:09:17
3             4        1         1  2006-02-15 05:09:17
4             5        1         2  2006-02-15 05:09:17

In [57]:
inv.film_id.unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  34,  35,  37,  39,  40,  42,  43,  44,
        45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
        58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
        84,  85,  86,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
        98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 109, 110, 111,
       112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
       125, 126, 127, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 145, 146, 147, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 172, 173, 174, 175, 176, 177, 178, 179, 180,
       181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 19

In [58]:
inv.store_id.unique()

array([1, 2], dtype=int64)

In [59]:
inv.last_update.unique()

array(['2006-02-15 05:09:17'], dtype=object)

In [60]:
inv.drop('last_update', axis=1, inplace=True)

In [85]:
inv.drop_duplicates(inplace = True)

In [86]:
inv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   inventory_id  1000 non-null   int64
 1   film_id       1000 non-null   int64
 2   store_id      1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB


In [62]:
inv.to_csv('../data/limpios/inventory_limpio.csv', index=False)

# Language
---

In [63]:
lan = pd.read_csv('../data/language.csv')
lan.head()

language_id      name          last_update
0            1   English  2006-02-15 05:02:19
1            2   Italian  2006-02-15 05:02:19
2            3  Japanese  2006-02-15 05:02:19
3            4  Mandarin  2006-02-15 05:02:19
4            5    French  2006-02-15 05:02:19

In [64]:
lan.last_update.unique()

array(['2006-02-15 05:02:19'], dtype=object)

In [66]:
lan.drop('last_update', axis=1, inplace=True)

In [87]:
lan.drop_duplicates(inplace = True)

In [88]:
lan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   language_id  6 non-null      int64 
 1   name         6 non-null      object
dtypes: int64(1), object(1)
memory usage: 224.0+ bytes


In [68]:
lan.to_csv('../data/limpios/language_limpio.csv', index=False)

# Rental
---

In [69]:
ren = pd.read_csv('../data/rental.csv')
ren.head()

rental_id          rental_date  inventory_id  customer_id   
0          1  2005-05-24 22:53:30           367          130  \
1          2  2005-05-24 22:54:33          1525          459   
2          3  2005-05-24 23:03:39          1711          408   
3          4  2005-05-24 23:04:41          2452          333   
4          5  2005-05-24 23:05:21          2079          222   

           return_date  staff_id          last_update  
0  2005-05-26 22:04:30         1  2006-02-15 21:30:53  
1  2005-05-28 19:40:33         1  2006-02-15 21:30:53  
2  2005-06-01 22:12:39         1  2006-02-15 21:30:53  
3  2005-06-03 01:43:41         2  2006-02-15 21:30:53  
4  2005-06-02 04:33:21         1  2006-02-15 21:30:53

In [72]:
ren.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   rental_id     1000 non-null   int64 
 1   rental_date   1000 non-null   object
 2   inventory_id  1000 non-null   int64 
 3   customer_id   1000 non-null   int64 
 4   return_date   1000 non-null   object
 5   staff_id      1000 non-null   int64 
 6   last_update   1000 non-null   object
dtypes: int64(4), object(3)
memory usage: 54.8+ KB


In [71]:
ren.rental_date.unique()[:10]

array(['2005-05-24 22:53:30', '2005-05-24 22:54:33',
       '2005-05-24 23:03:39', '2005-05-24 23:04:41',
       '2005-05-24 23:05:21', '2005-05-24 23:08:07',
       '2005-05-24 23:11:53', '2005-05-24 23:31:46',
       '2005-05-25 00:00:40', '2005-05-25 00:02:21'], dtype=object)

In [73]:
ren['rental_date'] = pd.to_datetime(ren['rental_date'], format='%Y-%m-%d %H:%M:%S')

In [74]:
ren.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   rental_id     1000 non-null   int64         
 1   rental_date   1000 non-null   datetime64[ns]
 2   inventory_id  1000 non-null   int64         
 3   customer_id   1000 non-null   int64         
 4   return_date   1000 non-null   object        
 5   staff_id      1000 non-null   int64         
 6   last_update   1000 non-null   object        
dtypes: datetime64[ns](1), int64(4), object(2)
memory usage: 54.8+ KB


In [75]:
ren.return_date.unique()[:10]

array(['2005-05-26 22:04:30', '2005-05-28 19:40:33',
       '2005-06-01 22:12:39', '2005-06-03 01:43:41',
       '2005-06-02 04:33:21', '2005-05-27 01:32:07',
       '2005-05-29 20:34:53', '2005-05-27 23:33:46',
       '2005-05-28 00:22:40', '2005-05-31 22:44:21'], dtype=object)

In [76]:
ren['return_date'] = pd.to_datetime(ren['return_date'], format='%Y-%m-%d %H:%M:%S')

In [77]:
ren.last_update.unique()

array(['2006-02-15 21:30:53'], dtype=object)

In [79]:
ren.drop('last_update', axis=1, inplace=True)

In [89]:
ren.drop_duplicates(inplace = True)

In [90]:
ren.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   rental_id     1000 non-null   int64         
 1   rental_date   1000 non-null   datetime64[ns]
 2   inventory_id  1000 non-null   int64         
 3   customer_id   1000 non-null   int64         
 4   return_date   1000 non-null   datetime64[ns]
 5   staff_id      1000 non-null   int64         
dtypes: datetime64[ns](2), int64(4)
memory usage: 47.0 KB


In [91]:
ren.to_csv('../data/limpios/rental_limpio.csv', index=False)

# Old HDD
---

In [93]:
old = pd.read_csv('../data/old_HDD.csv')
old.head()

first_name last_name                  title  release_year  category_id
0   PENELOPE   GUINESS       ACADEMY DINOSAUR          2006            6
1   PENELOPE   GUINESS   ANACONDA CONFESSIONS          2006            2
2   PENELOPE   GUINESS            ANGELS LIFE          2006           13
3   PENELOPE   GUINESS  BULWORTH COMMANDMENTS          2006           10
4   PENELOPE   GUINESS          CHEAPER CLYDE          2006           14

In [94]:
old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   first_name    1000 non-null   object
 1   last_name     1000 non-null   object
 2   title         1000 non-null   object
 3   release_year  1000 non-null   int64 
 4   category_id   1000 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 39.2+ KB


In [95]:
old.first_name.unique()

array(['PENELOPE', 'NICK', 'ED', 'JENNIFER', 'JOHNNY', 'BETTE', 'GRACE',
       'MATTHEW', 'JOE', 'CHRISTIAN', 'ZERO', 'KARL', 'UMA', 'VIVIEN',
       'CUBA', 'FRED', 'HELEN', 'DAN', 'BOB', 'LUCILLE', 'KIRSTEN',
       'ELVIS', 'SANDRA', 'CAMERON', 'KEVIN', 'RIP', 'JULIA', 'WOODY',
       'ALEC', 'SISSY', 'TIM', 'MILLA', 'AUDREY', 'JUDY', 'BURT', 'VAL',
       'TOM', 'GOLDIE'], dtype=object)

In [96]:
old.last_name.unique()

array(['GUINESS', 'WAHLBERG', 'CHASE', 'DAVIS', 'LOLLOBRIGIDA',
       'NICHOLSON', 'MOSTEL', 'JOHANSSON', 'SWANK', 'GABLE', 'CAGE',
       'BERRY', 'WOOD', 'BERGEN', 'OLIVIER', 'COSTNER', 'VOIGHT', 'TORN',
       'FAWCETT', 'TRACY', 'PALTROW', 'MARX', 'KILMER', 'STREEP', 'BLOOM',
       'CRAWFORD', 'MCQUEEN', 'HOFFMAN', 'WAYNE', 'PECK', 'SOBIESKI',
       'HACKMAN', 'DEAN', 'DUKAKIS', 'BOLGER', 'MCKELLEN', 'BRODY'],
      dtype=object)

In [97]:
old.release_year.unique()

array([2006], dtype=int64)

In [98]:
old.drop('release_year', axis=1, inplace=True)

In [99]:
old.drop_duplicates(inplace = True)

In [100]:
old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   first_name   1000 non-null   object
 1   last_name    1000 non-null   object
 2   title        1000 non-null   object
 3   category_id  1000 non-null   int64 
dtypes: int64(1), object(3)
memory usage: 31.4+ KB


In [101]:
old.to_csv('../data/limpios/old_hdd_limpio.csv', index=False)

Una vez limpiados todos los datos, el siguiente paso es organizar las relaciones entre las tablas.
  
Para ello usare MySQL Workbench

In [109]:
inv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   inventory_id  1000 non-null   int64
 1   film_id       1000 non-null   int64
 2   store_id      1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB


In [108]:
ren.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   rental_id     1000 non-null   int64         
 1   rental_date   1000 non-null   datetime64[ns]
 2   inventory_id  1000 non-null   int64         
 3   customer_id   1000 non-null   int64         
 4   return_date   1000 non-null   datetime64[ns]
 5   staff_id      1000 non-null   int64         
dtypes: datetime64[ns](2), int64(4)
memory usage: 47.0 KB


In [111]:
old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   first_name   1000 non-null   object
 1   last_name    1000 non-null   object
 2   title        1000 non-null   object
 3   category_id  1000 non-null   int64 
dtypes: int64(1), object(3)
memory usage: 31.4+ KB


In [116]:
inv.head(50)

inventory_id  film_id  store_id
0              1        1         1
1              2        1         1
2              3        1         1
3              4        1         1
4              5        1         2
5              6        1         2
6              7        1         2
7              8        1         2
8              9        2         2
9             10        2         2
10            11        2         2
11            12        3         2
12            13        3         2
13            14        3         2
14            15        3         2
15            16        4         1
16            17        4         1
17            18        4         1
18            19        4         1
19            20        4         2
20            21        4         2
21            22        4         2
22            23        5         2
23            24        5         2
24            25        5         2
25            26        6         1
26            27        6         1
27            28        6         1
28            29        6         2
29            30        6         2
30            31        6         2
31            32        7         1
32            33        7         1
33            34        7         2
34            35        7         2
35            36        7         2
36            37        8         2
37            38        8         2
38            39        8         2
39            40        8         2
40            41        9         1
41            42        9         1
42            43        9         1
43            44        9         2
44            45        9         2
45            46       10         1
46            47       10         1
47            48       10         1
48            49       10         1
49            50       10         2